#!/usr/bin/env node
/**
 * Generates supabase/migrations/0003_seed_places.sql from data/places.json so the
 * curated finder locations load as approved places. Idempotent (upsert on
 * source_ref). Run after editing data/places.json:  node tools/gen-seed.js
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const places = JSON.parse(fs.readFileSync(path.join(root, 'data/places.json'), 'utf8'));
const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

const rows = places.map((p) =>
  '  (' + [
    q('seed:' + p.id), q(p.name), q(p.type), q(p.state),
    p.lat, p.lng, q(p.desc), q('approved')
  ].join(', ') + ')'
).join(',\n');

const sql = `-- ============================================================================
-- Uvi — Phase B seed: curated finder locations
-- GENERATED by tools/gen-seed.js from data/places.json — do not edit by hand.
-- Idempotent: re-running upserts on source_ref.
-- ============================================================================

insert into public.places (source_ref, name, type, state, lat, lng, description, status)
values
${rows}
on conflict (source_ref) do update set
  name        = excluded.name,
  type        = excluded.type,
  state       = excluded.state,
  lat         = excluded.lat,
  lng         = excluded.lng,
  description = excluded.description,
  status      = 'approved';
`;

fs.writeFileSync(path.join(root, 'supabase/migrations/0003_seed_places.sql'), sql);
console.log(`Wrote supabase/migrations/0003_seed_places.sql with ${places.length} places.`);
