-- ============================================================================
-- Uvi — Phase B seed: curated finder locations
-- GENERATED by tools/gen-seed.js from data/places.json — do not edit by hand.
-- Idempotent: re-running upserts on source_ref.
-- ============================================================================

insert into public.places (source_ref, name, type, state, lat, lng, description, status)
values
  ('seed:p01', 'Lucky Bay, Cape Le Grand', 'freecamp', 'WA', -34.0006, 122.2286, 'Squeaky white sand and kangaroos on the beach — a beachside campground near Esperance.', 'approved'),
  ('seed:p02', 'Wilpena Pound, Flinders Ranges', 'park', 'SA', -31.5333, 138.6, 'Ancient natural amphitheatre with walking trails and a well-equipped park campground.', 'approved'),
  ('seed:p03', 'Tidal River, Wilsons Promontory', 'park', 'VIC', -39.03, 146.32, 'Southernmost mainland camping — beaches, granite peaks and abundant wildlife.', 'approved'),
  ('seed:p04', 'Karijini National Park', 'park', 'WA', -22.48, 118.28, 'Deep red gorges, waterfalls and swimming holes in the Pilbara.', 'approved'),
  ('seed:p05', 'The Tip, Cape York', 'track', 'QLD', -10.6875, 142.5315, 'Remote 4WD pilgrimage to the northernmost point of the Australian mainland.', 'approved'),
  ('seed:p06', '75 Mile Beach, K''gari', 'track', 'QLD', -25.35, 153.12, 'Iconic beach 4WD highway on the world''s largest sand island. Air down and check tides.', 'approved'),
  ('seed:p07', 'Big Red, Simpson Desert', 'track', 'QLD', -25.9, 139.35, 'The desert''s tallest dune, just west of Birdsville — the gateway to the Simpson crossing.', 'approved'),
  ('seed:p08', 'Blue Rag Range Track', 'track', 'VIC', -37.05, 147.12, 'Legendary High Country ridge run with 360° alpine views. Dry-weather only.', 'approved'),
  ('seed:p09', 'Coffin Bay', 'fishing', 'SA', -34.61, 135.47, 'Oysters, whiting and snapper on the Eyre Peninsula, with camps in the national park.', 'approved'),
  ('seed:p10', 'Ningaloo, Cape Range', 'fishing', 'WA', -22.14, 113.86, 'Reef right off the beach — snorkel with whale sharks and cast for pelagics.', 'approved'),
  ('seed:p11', 'Jervis Bay', 'fishing', 'NSW', -35.13, 150.69, 'White-sand bays, beach and boat fishing, and dolphin-filled waters.', 'approved'),
  ('seed:p12', 'Broome Caravan Park', 'caravan', 'WA', -17.96, 122.24, 'Base yourself near Cable Beach for Kimberley sunsets and camel trains.', 'approved'),
  ('seed:p13', 'Byron Bay Holiday Park', 'caravan', 'NSW', -28.64, 153.61, 'Powered sites minutes from the lighthouse walk and town beaches.', 'approved'),
  ('seed:p14', 'Alice Springs Tourist Park', 'caravan', 'NT', -23.7, 133.88, 'Central Red Centre base with amenities, dump point and easy resupply.', 'approved'),
  ('seed:p15', 'Coober Pedy', 'fuel', 'SA', -29.0139, 134.7544, 'Opal town and a vital Stuart Highway fuel and supply stop.', 'approved'),
  ('seed:p16', 'Birdsville Roadhouse', 'fuel', 'QLD', -25.8975, 139.3544, 'Last reliable fuel before the Simpson Desert crossing — fill everything.', 'approved'),
  ('seed:p17', 'Mount Dare Fuel', 'fuel', 'SA', -26.0561, 135.2394, 'Remote fuel and cold drinks on the western edge of the Simpson.', 'approved'),
  ('seed:p18', 'Katherine Dump Point', 'dump', 'NT', -14.465, 132.2635, 'Public RV dump point on the Stuart Highway between Darwin and the Centre.', 'approved'),
  ('seed:p19', 'Ceduna Dump Point', 'dump', 'SA', -32.126, 133.674, 'Handy waste stop before or after the Nullarbor crossing.', 'approved'),
  ('seed:p20', 'Mount Gambier Water Fill', 'water', 'SA', -37.8294, 140.7828, 'Potable water top-up near the Blue Lake on the Limestone Coast.', 'approved'),
  ('seed:p21', 'Hahndorf Water Point', 'water', 'SA', -35.0281, 138.81, 'Refill tanks in the Adelaide Hills before heading bush.', 'approved'),
  ('seed:p22', 'Johanna Beach, Great Ocean Road', 'freecamp', 'VIC', -38.75, 143.38, 'Wild, low-cost beachfront camping off the Great Ocean Road.', 'approved'),
  ('seed:p23', 'Mungo National Park', 'park', 'NSW', -33.72, 143.06, 'Remote outback park with ancient dunes and dark, star-filled skies.', 'approved'),
  ('seed:p24', 'Litchfield National Park', 'park', 'NT', -13.1, 130.78, 'Waterfalls and safe swimming holes within easy reach of Darwin.', 'approved')
on conflict (source_ref) do update set
  name        = excluded.name,
  type        = excluded.type,
  state       = excluded.state,
  lat         = excluded.lat,
  lng         = excluded.lng,
  description = excluded.description,
  status      = 'approved';
