-- ============================================================================
-- Uvi — Phase D: Social (follows, likes, comments, notifications)
-- Adds the social graph, engagement on trips, and in-app notifications
-- generated by triggers. Apply with:  supabase db push
-- ============================================================================

-- Engagement counters on trips (maintained by triggers below)
alter table public.trips add column if not exists like_count    integer not null default 0;
alter table public.trips add column if not exists comment_count integer not null default 0;

-- ----------------------------------------------------------------------------
-- follows
-- ----------------------------------------------------------------------------
create table if not exists public.follows (
  follower_id uuid references public.profiles(id) on delete cascade,
  followee_id uuid references public.profiles(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);
create index if not exists follows_followee_idx on public.follows (followee_id);

-- ----------------------------------------------------------------------------
-- likes (generic target; trips for now)
-- ----------------------------------------------------------------------------
create table if not exists public.likes (
  user_id     uuid references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('trip')),
  target_id   uuid not null,
  created_at  timestamptz not null default now(),
  primary key (user_id, target_type, target_id)
);
create index if not exists likes_target_idx on public.likes (target_type, target_id);

-- ----------------------------------------------------------------------------
-- comments (generic target; trips for now)
-- ----------------------------------------------------------------------------
create table if not exists public.comments (
  id          uuid primary key default gen_random_uuid(),
  target_type text not null check (target_type in ('trip')),
  target_id   uuid not null,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  body        text not null check (char_length(body) between 1 and 2000),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists comments_target_idx on public.comments (target_type, target_id, created_at);

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at
  before update on public.comments
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- notifications (written by triggers; read by the recipient)
-- ----------------------------------------------------------------------------
create table if not exists public.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,  -- recipient
  actor_id    uuid references public.profiles(id) on delete set null,
  type        text not null check (type in ('follow', 'like', 'comment')),
  target_type text,
  target_id   uuid,
  payload     jsonb not null default '{}',
  read_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index if not exists notifications_user_idx on public.notifications (user_id, created_at desc);

-- ----------------------------------------------------------------------------
-- Triggers: counters + notifications (security definer to bypass RLS)
-- ----------------------------------------------------------------------------
create or replace function public.likes_after()
returns trigger language plpgsql security definer set search_path = public as $$
declare owner_id uuid;
begin
  if tg_op = 'INSERT' and new.target_type = 'trip' then
    update public.trips set like_count = like_count + 1 where id = new.target_id;
    select user_id into owner_id from public.trips where id = new.target_id;
    if owner_id is not null and owner_id <> new.user_id then
      insert into public.notifications(user_id, actor_id, type, target_type, target_id)
      values (owner_id, new.user_id, 'like', 'trip', new.target_id);
    end if;
  elsif tg_op = 'DELETE' and old.target_type = 'trip' then
    update public.trips set like_count = greatest(like_count - 1, 0) where id = old.target_id;
  end if;
  return null;
end; $$;
drop trigger if exists likes_aid on public.likes;
create trigger likes_aid after insert or delete on public.likes
  for each row execute function public.likes_after();

create or replace function public.comments_after()
returns trigger language plpgsql security definer set search_path = public as $$
declare owner_id uuid;
begin
  if tg_op = 'INSERT' and new.target_type = 'trip' then
    update public.trips set comment_count = comment_count + 1 where id = new.target_id;
    select user_id into owner_id from public.trips where id = new.target_id;
    if owner_id is not null and owner_id <> new.user_id then
      insert into public.notifications(user_id, actor_id, type, target_type, target_id, payload)
      values (owner_id, new.user_id, 'comment', 'trip', new.target_id,
              jsonb_build_object('excerpt', left(new.body, 140)));
    end if;
  elsif tg_op = 'DELETE' and old.target_type = 'trip' then
    update public.trips set comment_count = greatest(comment_count - 1, 0) where id = old.target_id;
  end if;
  return null;
end; $$;
drop trigger if exists comments_aid on public.comments;
create trigger comments_aid after insert or delete on public.comments
  for each row execute function public.comments_after();

create or replace function public.follows_after()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications(user_id, actor_id, type)
  values (new.followee_id, new.follower_id, 'follow');
  return null;
end; $$;
drop trigger if exists follows_ai on public.follows;
create trigger follows_ai after insert on public.follows
  for each row execute function public.follows_after();

-- ----------------------------------------------------------------------------
-- RLS
-- ----------------------------------------------------------------------------
alter table public.follows       enable row level security;
alter table public.likes         enable row level security;
alter table public.comments      enable row level security;
alter table public.notifications enable row level security;

-- follows: public graph; you manage your own follows
drop policy if exists "read follows" on public.follows;
create policy "read follows" on public.follows for select using (true);
drop policy if exists "insert own follow" on public.follows;
create policy "insert own follow" on public.follows for insert to authenticated
  with check (follower_id = auth.uid());
drop policy if exists "delete own follow" on public.follows;
create policy "delete own follow" on public.follows for delete
  using (follower_id = auth.uid());

-- likes: public counts; you manage your own likes
drop policy if exists "read likes" on public.likes;
create policy "read likes" on public.likes for select using (true);
drop policy if exists "insert own like" on public.likes;
create policy "insert own like" on public.likes for insert to authenticated
  with check (user_id = auth.uid());
drop policy if exists "delete own like" on public.likes;
create policy "delete own like" on public.likes for delete using (user_id = auth.uid());

-- comments: readable when the target trip is visible; authors manage their own
drop policy if exists "read comments" on public.comments;
create policy "read comments" on public.comments for select using (
  target_type = 'trip' and exists (
    select 1 from public.trips t where t.id = comments.target_id
    and (t.is_public or t.user_id = auth.uid() or public.is_staff())
  )
);
drop policy if exists "insert own comment" on public.comments;
create policy "insert own comment" on public.comments for insert to authenticated
  with check (user_id = auth.uid());
drop policy if exists "update own comment" on public.comments;
create policy "update own comment" on public.comments for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "delete own or staff comment" on public.comments;
create policy "delete own or staff comment" on public.comments for delete
  using (user_id = auth.uid() or public.is_staff());

-- notifications: strictly private to the recipient
drop policy if exists "read own notifications" on public.notifications;
create policy "read own notifications" on public.notifications for select
  using (user_id = auth.uid());
drop policy if exists "update own notifications" on public.notifications;
create policy "update own notifications" on public.notifications for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ----------------------------------------------------------------------------
-- Grants
-- ----------------------------------------------------------------------------
grant select on public.follows to anon, authenticated;
grant insert, delete on public.follows to authenticated;
grant select on public.likes to anon, authenticated;
grant insert, delete on public.likes to authenticated;
grant select on public.comments to anon, authenticated;
grant insert, update, delete on public.comments to authenticated;
grant select, update on public.notifications to authenticated;
